.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH TABD 8 "APRIL 2016" Intel "TPM2 Software Stack"
.SH NAME
tabd \- TPM2 access broker daemon
.SH SYNOPSIS
.B tabd 
.RB [ \-l\ logger-name ]
.SH DESCRIPTION
.B tabd
is a daemon that implements the TPM access broker as described by the Trusted
Computing Group (TGC) in the
.B \*(lqTSS System Level API and TPM Command Transmission Interface
.B Specification\*(rq.
This daemon used DBus and some pipes to communicate with clients. Eventually,
it will implement the functionality of both both a TPM access broker (TAB)
and a resource manager (RM).
.SH OPTIONS
.TP
\fB\-l,\ \-\-logger\fR
Direct logging output to named logging target. Supported targets are
\fBstdout\fR and \fBsyslog\fR. If the logger option is not specified the
default is \fBstdout\fR.
.TP
\fB\-s,\ \-\-system\fR
Connect daemon to the system dbus. If this option is omitted the session bus
is used instead.
.SH ENVIRONMENT
none
.SH BUGS
lots
.SH AUTHOR
Philip Tricca <philip.b.tricca@intel.com>
.SH "SEE ALSO"
.BR tcsd (8)
