extraction:
  cpp:
    prepare:
      packages:
      - autoconf-archive
      - acl
    after_prepare:
    - cd "$LGTM_WORKSPACE"
    - mkdir installdir
    - git clone https://github.com/tpm2-software/tpm2-tss.git
    - cd tpm2-tss
    - ./bootstrap
    - ./configure --prefix="$LGTM_WORKSPACE/installdir/usr" --disable-doxygen-doc --disable-esys --disable-fapi
    - make install
    - export PKG_CONFIG_PATH="$LGTM_WORKSPACE/installdir/usr/lib/pkgconfig:$PKG_CONFIG_PATH"
    - export LD_LIBRARY_PATH="$LGTM_WORKSPACE/installdir/usr/lib:$LD_LIBRARY_PATH"
