#ifndef TSS2_TABD_H
#define TSS2_TABD_H

#include <tpm20.h>

#define TAB_DBUS_INTERFACE "com.intel.tss2.Tab"
#define TAB_DBUS_NAME "com.intel.tss2.Tab"
#define TAB_DBUS_PATH "/com/intel/tss2/Tab"
#define TAB_DBUS_METHOD_CREATE_CONNECTION "CreateConnection"
#define TAB_DBUS_METHOD_CANCEL "Cancel"

#define TSS2_TABRMD_INTERNAL_ERROR ((TSS2_RC)(1 << TSS2_LEVEL_IMPLEMENTATION_SPECIFIC_SHIFT) + TSS2_RESMGR_ERROR_LEVEL)
#define TSS2_TABRMD_SAPI_INIT      ((TSS2_RC)(2 << TSS2_LEVEL_IMPLEMENTATION_SPECIFIC_SHIFT) + TSS2_RESMGR_ERROR_LEVEL)
#define TSS2_TABRMD_OUT_OF_MEMORY  ((TSS2_RC)(3 << TSS2_LEVEL_IMPLEMENTATION_SPECIFIC_SHIFT) + TSS2_RESMGR_ERROR_LEVEL)
#define TSS2_TABRMD_BAD_VALUE  ((TSS2_RC)(3 << TSS2_LEVEL_IMPLEMENTATION_SPECIFIC_SHIFT) + TSS2_RESMGR_ERROR_LEVEL)

#endif /* TSS2_TABD_H */
