#ifndef TPM2_STRUCT_INIT
#define TPM2_STRUCT_INIT

#define TPM2B_STATIC_INIT(type) { \
    .t = { \
        .size = sizeof (type) - 2, \
    }, \
}
#define TPM2B_DIGEST_STATIC_INIT  TPM2B_STATIC_INIT(TPM2B_DIGEST)
#define TPM2B_NAME_STATIC_INIT    TPM2B_STATIC_INIT(TPM2B_NAME)
#define TPM2B_PUBLIC_STATIC_INIT  TPM2B_STATIC_INIT(TPM2B_PUBLIC)
#define TPM2B_PRIVATE_STATIC_INIT TPM2B_STATIC_INIT(TPM2B_PRIVATE)

#endif /* TPM2_STRUCT_INIT */
